### ISSUE TITLE
historykana doesn't work with OSX Japanese IME

### ISSUE THREAD

**Issue by adwd** [inuscript/historykana#33]
First of all, thank you for such a useful library 🙏 

I found that historykana works great with Google日本語入力, but it doesn't work when I use OSX ひらがな IME. :cry:

![historykana_fail](https://cloud.githubusercontent.com/assets/7473222/24037044/984d9fec-0b3f-11e7-9ce3-2328a1b8cbaa.gif)

**Comment by terrierscript** [comment]
Thank you for issue.
This may example website issue and not core library's bug.

I planned rewrite example page.

**Comment by adwd** [comment]
I tested with a tiny app, then cause seems to be that OSX ひらがな performs realtime 漢字変換. Because of that, input history is different from one which `historykana` expects. Tested code is [here](https://github.com/adwd/test-historykana).

input history of 山田 with ...
- Google 日本語入力 ひらがな
  - `ｙ, や, やｍ, やま, やまｄ, やまだ, 山田`
- OSX ひらがな
  - `y, や, やm, 山, 山d, 山田`
    - problem is `やま` and `山だ` are skipped...?

![historykana](https://cloud.githubusercontent.com/assets/7473222/24071238/85b04aa2-0c10-11e7-810d-0031472e31cb.gif)

**Comment by terrierscript** [comment]
Thank you testing.

> problem is やま and 山だ are skipped...?

I think so too. 
Sadly, if cannot capture skipped words from `OSX ひらがな`, this library's logic cannot solve this issue.

**Comment by adwd** [comment]
Thank you for reply! I understood 😢 
I'll close this issue.
