### ISSUE TITLE
Correct URL on github description

### ISSUE THREAD

**Issue by sideroad** [inuscript/historykana#36]
```
Japanese furigana library http://inuscript.github.io/react-auto-kana/
```

might need to fix to below instead.
```
Japanese furigana library http://terrierscript.github.io/react-auto-kana/
```

**Comment by sideroad** [comment]
<img width="673" alt="スクリーンショット 2019-04-01 午後11 17 34" src="https://user-images.githubusercontent.com/411486/55334498-5c4f1f80-54d4-11e9-9c18-7eab556f411d.png">

**Comment by terrierscript** [comment]
Thank you! fixed it
